/**
 * generic
 */
export const UPDATE_STICKY_STATE = 'UPDATE_STICKY_STATE';
export const SET_FILTER_TEXT = 'SET_FILTER_TEXT';
export const RESET_DETAIL_STORE = 'RESET_DETAIL_STORE';
export const UPDATE_ALL = 'UPDATE_ALL';

/**
 * datasets
 */
export const SET_IS_PROCESSING = 'SET_IS_PROCESSING';
export const SET_IS_SYNCING = 'SET_IS_SYNCING';
export const SET_IS_EXPORTING = 'SET_IS_EXPORTING';

/**
 * environment
 */
export const CLOSE_ENVIRONMENT_MENUS = 'CLOSE_ENVIRONMENT_MENUS';
export const TOGGLE_ADVANCED_VISIBLE = 'TOGGLE_ADVANCED_VISIBLE';
export const CONTAINER_MENU_WARNING = 'CONTAINER_MENU_WARNING';
export const UPDATE_CONTAINER_MENU_VISIBILITY = 'UPDATE_CONTAINER_MENU_VISIBILITY';

/**
 * packageDependencies
 */
export const TOGGLE_PACKAGE_MENU = 'TOGGLE_PACKAGE_MENU';


/**
 * overview
 */
export const UPDATE_CONTAINER_STATE = 'UPDATE_CONTAINER_STATE';
export const RESET_OVERVIEW_STORE = 'RESET_OVERVIEW_STORE';

/**
 * container status
 */
export const UPDATE_CONTAINER_STATUS = 'UPDATE_CONTAINER_STATUS';
export const IS_LOOKING_UP_PACKAGES = 'IS_LOOKING_UP_PACKAGES';


/**
 * labboook
 */
export const INITIATE_NAMESPACE = 'INITIATE_NAMESPACE';
export const INITIALIZE = 'INITIALIZE';
export const IS_BUILDING = 'IS_BUILDING';
export const IS_SYNCING = 'IS_SYNCING';
export const IS_UPLOADING = 'IS_UPLOADING';
export const IS_EXPORTING = 'IS_EXPORTING';
export const IS_PUBLISHING = 'IS_PUBLISHING';
export const MODAL_VISIBLE = 'MODAL_VISIBLE';
export const SELECTED_COMPONENT = 'SELECTED_COMPONENT';
export const UPDATE_BRANCHES_VIEW = 'UPDATE_BRANCHES_VIEW';
export const UPDATE_SIDEPANEL_VISIBLE = 'UPDATE_SIDEPANEL_VISIBLE';
export const MERGE_MODE = 'MERGE_MODE';
export const UPDATE_TRANSITION_STATE = 'UPDATE_TRANSITION_STATE';

/**
 * collaborators
 */
export const SET_COLLABORATORS = 'SET_COLLABORATORS';
export const SET_CANMANAGECOLLABORATORS = 'SET_CANMANAGECOLLABORATORS';


/**
 * file browser
 */
export const FINISHED_UPLOADING = 'FINISHED_UPLOADING';
export const STARTED_UPLOADING = 'STARTED_UPLOADING';
export const PAUSE_UPLOAD = 'PAUSE_UPLOAD';
export const PAUSE_UPLOAD_DATA = 'PAUSE_UPLOAD_DATA';
export const PAUSE_CHUNK_UPLOAD = 'PAUSE_CHUNK_UPLOAD';
export const RESET_CHUNK_UPLOAD = 'RESET_CHUNK_UPLOAD';

/**
 * footer
 */
// messages that have a constant state
export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export const INFO_MESSAGE = 'INFO_MESSAGE';
export const WARNING_MESSAGE = 'WARNING_MESSAGE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';
// loaders with updating state
// file updating
export const UPLOAD_MESSAGE_SETTER = 'UPLOAD_MESSAGE_SETTER';
export const UPLOAD_MESSAGE_UPDATE = 'UPLOAD_MESSAGE_UPDATE';
export const UPLOAD_MESSAGE_REMOVE = 'UPLOAD_MESSAGE_REMOVE';
export const IMPORT_MESSAGE_SUCCESS = 'IMPORT_MESSAGE_SUCCESS';
//
export const RESET_FOOTER_STORE = 'RESET_FOOTER_STORE';
export const TOGGLE_MESSAGE_LIST = 'TOGGLE_MESSAGE_LIST';
export const HIDE_MESSAGE_LIST = 'HIDE_MESSAGE_LIST';

export const MULTIPART_INFO_MESSAGE = 'MULTIPART_INFO_MESSAGE';

export const UPDATE_MESSAGE_STACK_ITEM_VISIBILITY = 'UPDATE_MESSAGE_STACK_ITEM_VISIBILITY';
export const UPDATE_HISTORY_STACK_ITEM_VISIBILITY = 'UPDATE_HISTORY_STACK_ITEM_VISIBILITY';


export const RESIZE_FOOTER = 'RESIZE_FOOTER';
export const UPDATE_HISTORY_VIEW = 'UPDATE_HISTORY_VIEW';
export const HELPER_VISIBLE = 'HELPER_VISIBLE';


/**
 * helper
 */
export const UPDATE_HELPER_VISIBILITY = 'UPDATE_HELPER_VISIBILITY';
export const RESIZE_HELPER = 'RESIZE_HELPER';


/**
 * login
 */
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_CLEAR = 'LOGIN_CLEAR';
export const LOGOUT = 'LOGOUT';

/**
 * routes
 */
export const UPDATE_LABBOOKNAME = 'UPDATE_LABBOOKNAME';
export const UPDATE_OWNER = 'UPDATE_OWNER';
export const UPDATE_CALLBACK_ROUTE = 'UPDATE_CALLBACK_ROUTE';
