FROM gigantum/circleci-common:84814eab-2018-07-25
LABEL maintainer="Gigantum <hello@gigantum.io>"

USER root

# Install python deps and testing deps
COPY submodules/labmanager-service-labbook/requirements.txt /opt/labmanager-service-labbook_requirements.txt
COPY submodules/labmanager-service-labbook/requirements-testing.txt /opt/labmanager-service-labbook_requirements-testing.txt
RUN pip3 install -r /opt/labmanager-service-labbook_requirements.txt && \
    pip3 install -r /opt/labmanager-service-labbook_requirements-testing.txt

# Install Proxy
RUN apt-get -y install curl gnupg gnupg2 gnupg1 && curl -sL https://deb.nodesource.com/setup_8.x | bash
RUN apt-get -y install nodejs && npm install -g configurable-http-proxy

# Setup share dir
RUN mkdir /mnt/share && chown -R circleci:circleci /mnt/share

# Finish setting up user
USER circleci
WORKDIR /home/circleci

CMD ["/bin/bash"]
