FROM ubuntu:18.04
LABEL maintainer="Gigantum <hello@gigantum.io>"

# Copy requirements.txt files
COPY submodules/labmanager-common/requirements.txt /opt/labmanager-common_requirements.txt
COPY submodules/labmanager-common/requirements-testing.txt /opt/labmanager-common_requirements-testing.txt
COPY submodules/labmanager-service-labbook/requirements.txt /opt/labmanager-service-labbook_requirements.txt
COPY submodules/labmanager-service-labbook/requirements-testing.txt /opt/labmanager-service-labbook_requirements-testing.txt

ENV SHELL=/bin/bash

RUN apt-get -y update && \
    apt-get -y --no-install-recommends install git nginx supervisor wget openssl python3 python3-pip python3-distutils \
    vim emacs zip unzip curl nodejs npm \
    gcc g++ gosu redis-server libjpeg-dev git-lfs python3-setuptools python3-dev libdpkg-perl && \
    git lfs install && \
    pip3 install wheel

RUN npm install -g configurable-http-proxy && \
    git clone https://github.com/gigantum/confhttpproxy.git && pip3 install -e confhttpproxy

RUN pip3 install -r /opt/labmanager-common_requirements.txt && \
    pip3 install -r /opt/labmanager-common_requirements-testing.txt && \
    pip3 install -r /opt/labmanager-service-labbook_requirements.txt && \
    pip3 install -r /opt/labmanager-service-labbook_requirements-testing.txt && \
    pip3 install uwsgi

RUN npm install yarn --global

# Setup path and python path
ENV PYTHONPATH=$PYTHONPATH:/opt/project/gtmlib/resources/submodules/labmanager-common

# Setup lmcommon config file - should be written by automation before copy
COPY developer_resources/labmanager-config.yaml /etc/gigantum/labmanager.yaml

# Setup logging config file
COPY submodules/labmanager-common/lmcommon/logging/logging.json.default /etc/gigantum/logging.json

# Make working dir and code mount points
RUN mkdir -p /mnt/gigantum && mkdir /opt/node_build

# Setup Redis
RUN mkdir /opt/redis
COPY labmanager_resources/redis.conf /opt/redis/redis.conf

# Setup Supervisord to launch redis and rq
RUN mkdir -p /opt/log/supervisor; mkdir -p /opt/run;
COPY labmanager_resources/supervisord_base.conf /etc/supervisor/supervisord.conf
COPY developer_resources/supervisord-configured.conf /etc/supervisor/conf.d/supervisord.conf

COPY developer_resources/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod u+x /usr/local/bin/entrypoint.sh

# Setup demo labbook
COPY awful-intersections-demo.lbk /opt/awful-intersections-demo.lbk

# Expose Ports
EXPOSE 10000
EXPOSE 10001
EXPOSE 10002

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["/bin/bash"]
