FROM ubuntu:18.04
LABEL maintainer="Gigantum <hello@gigantum.io>"

# Copy requirements files
COPY packages/gtmcore/requirements.txt /opt/labmanager-common/requirements.txt
COPY packages/gtmapi/requirements.txt /opt/labmanager-service-labbook/requirements.txt
COPY packages/gtmconfhttpproxy /opt/gtmconfhttpproxy
ENV SHELL=/bin/bash

# Super instruction to install all dependencies
RUN apt-get -y update && \
    apt-get -y --no-install-recommends install git nginx supervisor wget openssl python3 python3-pip python3-distutils \
    gcc g++ gosu redis-server libjpeg-dev git-lfs python3-setuptools python3-dev libdpkg-perl zip unzip && \
    git lfs install && \
    apt-get -y install curl gnupg gnupg1 gnupg2 && \
    curl -sL https://deb.nodesource.com/setup_8.x | bash && \
    apt-get -y install nodejs && \
    npm install -g configurable-http-proxy && \
    cd /opt/gtmconfhttpproxy && pip3 install -e . && \
    pip3 install wheel && \
    pip3 install -r /opt/labmanager-common/requirements.txt && \
    pip3 install -r /opt/labmanager-service-labbook/requirements.txt && \
    pip3 install uwsgi && \
    apt-get -qq -y remove gcc g++ python3-dev wget curl gnupg gnupg1 gnupg2 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /var/log/dpkg.log

# Copy Libraries
COPY packages/gtmapi /opt/gtmapi
COPY packages/gtmcore /opt/gtmcore

RUN cd /opt/gtmcore/ && python3 setup.py install

# Setup lmcommon config file - should be written by automation before copy
COPY resources/labmanager_resources/labmanager-config.yaml /etc/gigantum/labmanager.yaml

# Setup logging config file
COPY packages/gtmcore/gtmcore/logging/logging.json.default /etc/gigantum/logging.json

# Make needed directories
RUN mkdir -p /mnt/gigantum && mkdir /opt/redis

# Copy frontend
COPY build/build/build/ /var/www/

# Setup NGINX/uWSGI
COPY resources/labmanager_resources/nginx_ui.conf /etc/nginx/sites-enabled/
COPY resources/labmanager_resources/nginx_api.conf /etc/nginx/sites-enabled/
RUN rm /etc/nginx/sites-enabled/default

# Setup Redis
COPY resources/labmanager_resources/redis.conf /opt/redis/redis.conf

# Setup Supervisord to launch both uwsgi and nginx
RUN mkdir -p /opt/log/supervisor && mkdir -p /opt/log/nginx && mkdir -p /opt/run && \
    mkdir -p /opt/nginx && nginx && nginx -s reload && nginx -s quit
COPY resources/labmanager_resources/supervisord_base.conf /etc/supervisor/supervisord.conf
COPY resources/labmanager_resources/supervisord-configured.conf /etc/supervisor/conf.d/supervisord.conf

COPY resources/labmanager_resources/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod u+x /usr/local/bin/entrypoint.sh

# Setup demo labbook
COPY resources/awful-intersections-demo.lbk /opt/awful-intersections-demo.lbk

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

# Expose Ports
EXPOSE 10000
EXPOSE 10001
EXPOSE 10002

# Start by firing up uwsgi, nginx, redis, and workers via supervisord
CMD ["/usr/bin/supervisord", "--nodaemon"]
