FROM ubuntu:18.04
LABEL maintainer="Gigantum <hello@gigantum.io>"

# Copy requirements.txt files
COPY submodules/labmanager-common/requirements.txt /opt/labmanager-common_requirements.txt
COPY submodules/labmanager-common/requirements-testing.txt /opt/labmanager-common_requirements-testing.txt
ENV SHELL=/bin/bash \
    GTM_DEVELOPER=1

# Install system level dependencies
RUN apt-get -y update && \
    apt-get -y --no-install-recommends install git nginx supervisor wget openssl python3 python3-pip python3-distutils \
    gcc g++ gosu redis-server libjpeg-dev git-lfs python3-setuptools python3-dev libdpkg-perl ssh zip unzip && \
    pip3 install wheel

# Setup circleci user
RUN useradd -ms /bin/bash circleci

# Install python deps and testing deps
RUN pip3 install -r /opt/labmanager-common_requirements.txt && \
    pip3 install -r /opt/labmanager-common_requirements-testing.txt && \
    pip3 install coveralls pytest-cov pytest-xdist

# Set up working dir, required for import mocks
RUN mkdir -p /mnt/gigantum && chown -R circleci:circleci /mnt/gigantum && \
    mkdir /home/circleci/gigantum && chown -R circleci:circleci /home/circleci/gigantum

# Finish setting up user
USER circleci
WORKDIR /home/circleci

CMD ["/bin/bash"]
