version: '2'
services:
  labmanager:
    image: gigantum/labmanager-dev:latest
    entrypoint: /usr/local/bin/entrypoint.sh
    command: /bin/bash
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - {% WORKING_DIR %}:/mnt/gigantum:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - {% GTM_DIR %}:/opt/project/:cached
      - labmanager_share_vol:/mnt/share
      - {% HELPER_SCRIPT %}:/opt/setup.sh
    environment:
      - SET_PERMISSIONS=/opt/project/packages
      - LOCAL_USER_ID={% USER_ID %}
      - HOST_WORK_DIR={% WORKING_DIR %}
      - NVIDIA_DRIVER_VERSION=${NVIDIA_DRIVER_VERSION}
    network_mode: "bridge"

volumes:
  labmanager_share_vol:
    external: true
